// Every piece of on-screen text lives here.
// Headlines: `*word*` renders the word with the brand accent gradient.
// All names, phone numbers and order numbers below are fictional.

export const COPY = {
  overload: {
    headline1: ['Commandet.', 'Réservations. Messaget.'],
    headline2: ['*El kol fi wa9t wa7ed.*'],
    lockTime: '19:42',
    lockDate: 'Jeudi 2 octobre',
  },
  split: {
    headline1: ['Insta, Messenger,', '*el site…*'],
    headline2: ['Ma tal7a9ch', '*tjaweb el kol.*'],
  },
  consequences: {
    clocks: ['23:00', '02:00', '08:00'],
    headline: ['Kol jweb m3a5er', '= *client mcha l ghirek.*'],
    seen: 'Vu',
    dmName: 'Amine K.',
    dmFirst: 'chhal soumha?',
    dmQ1: '?',
    dmQ2: '??',
    dmLeave: 'Bon, nchri men 3and ghirkom.',
    cancelledTitle: 'Commande #318604',
    cancelledStatus: 'Tbattlet',
    cancelledSub: 'Ma jawbouch · 129 TND',
    tableTitle: 'Tawla 6 · 20:30',
    tableStatus: 'Far8a',
    tableSub: 'Ma t2akkdetch el réservation',
    lostLabel: 'Ventes dhay3a',
    lostValue: 2460,
    currency: 'TND',
  },
  reveal: {
    headline1: ['Hedha *MERCHATI*,', 'el employé IA mte3ek.'],
    headline2: ['Yjaweb 3la kol message.', '*Bel darija. Lil w nhar.*'],
    answered: 'Répondu',
    rows: [
      {app: 'ig', name: 'sarra.jl', reply: 'Ey, famma taille M ✅ 89 DT', time: '4 s'},
      {app: 'ms', name: 'Mehdi Gharbi', reply: 'Table l 4 ghodwa 20h ✅', time: '6 s'},
      {app: 'shop', name: 'Commande #482633', reply: 'Confirmée · 74 TND', time: '3 s'},
      {app: 'ig', name: 'ines.bnamor', reply: 'Livraison l Sousse 24–48h 🚚', time: '5 s'},
      {app: 'resa', name: 'Réservation · 6 pers.', reply: 'Samedi 21:00 · confirmée ✅', time: '7 s'},
      {app: 'ig', name: 'yosr_tn', reply: 'Commande #482641 fi thnia 🚚', time: '4 s'},
    ],
  },
  shopDM: {
    headline1: ['Sou2el?', '*Jweb fi thawani.*'],
    headline2: ['Ya5ou', '*el commande.*'],
    headline3: ['Yefhem', '*7atta el vocal.*'],
    shopName: 'Maison Lina',
    shopHandle: 'maisonlina.tn',
    customer1: '3aslema, chhal soum el robe\nel ka7la? famma M?',
    ai1: "3aslema 🤍 El robe el ka7la b 89 DT.\nTaille M famma ✅ Chouf l'alwen :",
    customer2: 'el ka7la, taille M 👌',
    ai2: 'Behi! A3tini esmek, noumrou\nw l’adresse mte3ek 🙏',
    customer3: 'Amira Ben Salah\n+216 •• ••• 482\nSousse, Khezama',
    customer4: 'ey confirmé',
    ai3: 'Commande #482913 ✅\nYa3tik saha Amira! Livraison 24–48h.',
    transcriptLabel: 'Vocal → texte',
    transcript: '« w tousel l Monastir zeda ? »',
    ai4: 'Ey, tousel l Monastir zeda 🚚\nLivraison 7 DT, 24–48h.',
    voiceDuration: '0:06',
    badge: 'Yjaweb fi < 30 s · 24/7',
    aiChip: 'MERCHATI AI',
    composer: 'Message…',
  },
  products: [
    {name: 'Robe Satin', color: 'Noir', price: '89 TND'},
    {name: 'Robe Satin', color: 'Beige', price: '89 TND'},
    {name: 'Robe Satin', color: 'Bordeaux', price: '89 TND'},
  ],
  recap: {
    title: 'Récap el commande',
    product: 'Robe Satin — Noir',
    variant: 'Taille M · Couleur Noir',
    delivery: 'Livraison · Sousse',
    deliveryValue: '7 TND',
    subtotal: 'Article',
    subtotalValue: '89 TND',
    total: 'Total',
    totalValue: '96 TND',
    question: 'Confirmé ?',
    payment: 'Paiement à la livraison',
  },
  telegram: {
    headline: ['Alerte tol', '*3la Telegram.*'],
    chatName: 'MERCHATI Alerts',
    chatSub: 'bot',
    bannerApp: 'Telegram',
    bannerTitle: 'MERCHATI Alerts',
    bannerBody: '🛍️ Nouvelle commande #482913',
    olderAlert: '🛍️ Nouvelle commande #482877\nSarra J. · 64 TND',
    order: {
      title: '🛍️ Nouvelle commande #482913',
      lines: [
        '👤 Amira Ben Salah',
        '📞 +216 •• ••• 482',
        '👗 Robe Satin — Noir — M',
        '📍 Sousse, Khezama',
        '💰 Total : 96 TND (livraison 7 TND)',
      ],
      time: '20:14',
    },
    booking: {
      title: '📅 Nouvelle réservation #R73015',
      lines: [
        '👤 Yassine Trabelsi',
        '📞 +216 •• ••• 915',
        '🕗 Ghodwa · 20:00 · 4 pers.',
        '🪑 Tawla T19 · Banquette',
      ],
      time: '18:32',
    },
  },
  shopDash: {
    headline: ['Kol commande', '*fi dashboard wa7da.*'],
    groups: [
      {group: 'WORKSPACE', items: ['Dashboard', 'Chat Monitor', 'Connections']},
      {group: 'STORE & ORDERS', items: ['Products', 'StoryReply', 'Delivered Products', 'Order Issues']},
      {group: 'INTELLIGENCE', items: ['AI Settings']},
      {group: 'ACCOUNT & PLAN', items: ['Subscription & Plan', 'Settings']},
    ],
    welcome: 'Welcome back, Maison Lina',
    welcomeSub: 'Here’s what your AI agent has been up to.',
    capacity: {tier: 'ELITE', title: 'AI Message Capacity', available: '(4 870 messages available)', note: 'Monthly plan messages reset periodically. Extra purchased packages never expire.', used: '1 130 / 6 000', extra: '500 left', button: 'Buy Extra Messages', progress: 0.19},
    kpis: [
      {label: 'Total Revenue', value: 18640, suffix: ' TND'},
      {label: 'Total Messages', value: 1214, suffix: ''},
      {label: 'Active Leads', value: 87, suffix: ''},
      {label: 'AI Responses', value: 1196, suffix: ''},
    ],
    activityTitle: 'Recent Activity',
    activityLink: 'Open Chat Monitor →',
    activity: [
      {name: 'Yasmine Ben Ali', text: 'famma taille S fil robe el beige? → Ey famma ✅'},
      {name: 'Mohamed Amine Trabelsi', text: 'el sneakers fi 42 mawjoudin? → Ey, 159 DT 👟'},
      {name: 'Rania Gharbi', text: 'win el commande mte3i? → Fi thnia, tousel ghodwa 🚚'},
    ],
    radarTitle: 'Demand Radar',
    radarSub: 'Products customers want that are unavailable',
    radar: [
      {product: 'Robe Satin — Bordeaux · M', count: '12 requests'},
      {product: 'Hoodie Oversize — Vert · XL', count: '7 requests'},
    ],
    fulfillment: 'FULFILLMENT',
    tableTitle: 'Delivered Orders',
    tableSub: 'Track orders processed and delivered through AI Chatbot integrations.',
    search: 'Search orders…',
    totalRevenueLabel: 'TOTAL REVENUE',
    totalRevenueFrom: 4766,
    totalRevenueTo: 4862,
    fulfilledLabel: 'FULFILLED',
    fulfilledFrom: 37,
    columns: ['CLIENT NAME', 'PRODUCT', 'SIZE', 'COLOR', 'PRICE', 'PHONE / EMAIL', 'ADDRESS', 'STATUS'],
    newRow: {id: '#A48291', name: 'Amira Ben Salah', product: 'Robe Satin', size: 'M', color: 'Noir', dot: '#17171A', price: '96.00', phone: '+216 •• ••• 482', email: 'a•••••@gmail.com', address: 'Khezama, Sousse', status: 'New'},
    rows: [
      {id: '#K27E6A', name: 'Yasmine Ben Ali', product: 'Robe Satin', size: 'S', color: 'Beige', dot: '#D9C3A5', price: '96.00', phone: '+216 •• ••• 127', email: 'y•••••@gmail.com', address: 'Lac 2, Tunis', status: 'Delivered'},
      {id: '#D1F815', name: 'Mohamed Amine T.', product: 'Sneakers Cuir', size: '42', color: 'Blanc', dot: '#E8E8E8', price: '166.00', phone: '+216 •• ••• 390', email: 'm•••••@gmail.com', address: 'Gremda, Sfax', status: 'Delivered'},
      {id: '#F8DE7A', name: 'Rania Gharbi', product: 'Sac Bandoulière', size: '—', color: 'Noir', dot: '#17171A', price: '94.00', phone: '+216 •• ••• 654', email: 'r•••••@gmail.com', address: 'Hammamet, Nabeul', status: 'Pending'},
      {id: '#84A8D2', name: 'Oussama Jlassi', product: 'Hoodie Oversize', size: 'L', color: 'Vert', dot: '#3F7D4E', price: '86.00', phone: '+216 •• ••• 211', email: 'o•••••@gmail.com', address: 'Skanes, Monastir', status: 'Delivered'},
    ],
    statusNew: 'New',
    statusConfirmed: 'Confirmed',
    statusDelivery: 'In delivery',
    incl: 'incl. 7.00 delivery',
    actions: ['Send to delivery', 'Confirmed by phone', "Didn't answer", 'Decline'],
    toast: 'Synced with Converty',
  },
  restoDM: {
    headline0: ['T7eb tawla?', '*Yeb3ethlek el lien.*'],
    headline: ['Tawlet ta3mer', '*wa7adha.*'],
    venueName: 'Dar Yasmine',
    venueTagline: 'Cuisine tunisienne · Terrasse',
    siteClose: 'OK',
    venueSub: 'Active now',
    customer1: 'famma table l 4 ghodwa 20h?',
    ai1: 'Ahla bik 🌙 Ey famma!\nIkhtar tawoltek houni 👇',
    linkTitle: 'Dar Yasmine — Réserver une table',
    linkUrl: 'dar-yasmine.merchati.tn',
    composer: 'Aa',
    siteUrl: 'dar-yasmine.merchati.tn',
    siteTitle: 'Ikhtar tawoltek',
    siteMeta: ['Ghodwa', '20:00', '4 pers.'],
    sheetTitle: 'Tawla T19 · Banquette',
    sheetSub: '4 blayes · Ghodwa 20:00',
    sheetButton: 'Réservi el tawla',
    confirmedTitle: 'Réservation confirmée ✅',
    confirmedSub: '#R73015 · Ghodwa · 20:00 · 4 pers.',
    free: 'Far8a',
    taken: 'Réservée',
  },
  restoDash: {
    headline: ['Kol réservation,', '*en direct.*'],
    groups: [
      {group: 'LIVE SERVICE', items: ['Tonight', 'Chat Monitor', 'Reservations']},
      {group: 'RESTAURANT', items: ['Tables', 'Menu', 'Branding & Operations']},
      {group: 'AUTOMATION', items: ['Connections', 'AI Settings']},
      {group: 'ACCOUNT & PLAN', items: ['Subscription & Plan', 'Settings']},
    ],
    serviceOpen: 'SERVICE OPEN',
    greeting: 'Good evening',
    date: 'jeudi 2 octobre',
    summary: '14 bookings tonight. Guests reserve tables via your public booking page.',
    publicPage: 'View Public Booking Page (dar-yasmine.merchati.tn)',
    printSheet: 'Print Shift Run Sheet (PDF)',
    exportCsv: 'Export CSV',
    seats: 46,
    seatsTotal: 72,
    ringSub: 'Live floor plan availability synchronized.',
    stats: [
      {label: 'TODAY BOOKINGS', value: '14', sub: 'reservations'},
      {label: 'TOTAL TABLES', value: '21', sub: '72 seats total capacity'},
      {label: "DISHES 86'D", value: '0', sub: 'full menu on'},
    ],
    floorTitle: 'Active Floor Plan',
    manageTables: 'Manage Tables →',
    bookEyebrow: 'LIVE CLOUD DATABASE',
    bookTitle: 'Reservations & Bookings (The Book)',
    bookSub: 'Manage guest bookings with 3-hour conflict protection.',
    upcoming: 'Upcoming Only',
    showAll: 'Show All',
    newRes: {time: '20:00', guests: '4 guests', name: 'Yassine Trabelsi', table: 'Table T19', date: '2026-10-03', phone: '+216 •• ••• 915', status: 'Confirmed'},
    reservations: [
      {time: '19:30', guests: '2 guests', name: 'Mariem Ayari', table: 'Table T03', date: '2026-10-03', phone: '+216 •• ••• 274', status: 'Confirmed'},
      {time: '20:30', guests: '6 guests', name: 'Hamza Ben Youssef', table: 'Table T14', date: '2026-10-03', phone: '+216 •• ••• 608', status: 'Confirmed'},
      {time: '21:00', guests: '10 guests', name: 'Nour Chaabane', table: 'Table T11', date: '2026-10-03', phone: '+216 •• ••• 731', status: 'Confirmed'},
      {time: '21:30', guests: '2 guests', name: 'Karim Mejri', table: 'Table T16', date: '2026-10-03', phone: '+216 •• ••• 156', status: 'Cancelled'},
    ],
    seated: 'Seated',
    noShow: 'No-show',
    del: 'Delete',
    confirm: 'Confirm',
  },
  highlights: [
    'Darija tounsia 100%',
    'Yefhem el vocal',
    'Sync Converty & Shopify',
    'Tnajjem tod5el wa9t ma t7eb',
  ],
  pricing: {
    headline: ['Soum m3a9oul,', '*bla surprises.*'],
    plans: [
      {name: 'E-commerce', from: 'Ybda men', price: 50, unit: 'DT / ch’har', setup: ''},
      {name: 'Restaurant & Café', from: 'Ybda men', price: 60, unit: 'DT / ch’har', setup: '+ 150 DT setup (marra wa7da)'},
    ],
  },
  cta: {
    lines: ['Kol message 3andou jweb.', 'Bi3 wala réservation.', '*Bel darija.*'],
    pill: '7 iyem blech — bla carte bancaire',
    url: 'merchati.tn',
    lockTime: '08:00',
    lockDate: 'Vendredi 3 octobre',
    summary: [
      {app: 'Instagram', title: '47 conversation jawebhom', sub: 'MERCHATI AI'},
      {app: 'Boutique', title: '12 commandet confirmés', sub: '1 148 TND · paiement à la livraison'},
      {app: 'Réservations', title: '9 tawlet réservés', sub: 'Ellila · Dar Yasmine'},
    ],
  },
  // Notification flood (Part 1). app: ig | ms | shop | resa
  notifications: [
    {app: 'ig', title: 'sarra.jl', body: '3aslema, chhal soumha?'},
    {app: 'ms', title: 'Mehdi Gharbi', body: 'famma table l 4 ghodwa 20h?'},
    {app: 'shop', title: 'Nouvelle commande', body: 'Commande #482633 · 74 TND'},
    {app: 'ig', title: 'ines.bnamor', body: 'famma taille M?'},
    {app: 'resa', title: 'Demande de réservation', body: 'Réservation 6 personnes?'},
    {app: 'ms', title: 'Rym Chaouch', body: 'livraison l Sousse?'},
    {app: 'ig', title: 'yosr_tn', body: 'win el commande mte3i?'},
    {app: 'shop', title: 'Nouvelle commande', body: 'Commande #482641 · 129 TND'},
    {app: 'ig', title: 'aziz.ks', body: 'el prix 9adeh?'},
    {app: 'resa', title: 'Demande de réservation', body: 'Table l 2 ellila 21h?'},
    {app: 'ms', title: 'Hela Ben Ali', body: 'famma lawn akhor?'},
    {app: 'ig', title: 'nour.ch', body: 'Bonsoir, dispo en L?'},
    {app: 'shop', title: 'Nouvelle commande', body: 'Commande #482655 · 58 TND'},
    {app: 'ig', title: 'mariem_a', body: 'tbadlouha ken mat9adech?'},
    {app: 'ms', title: 'Khalil Mansour', body: 'mazelt majetnich el commande'},
    {app: 'resa', title: 'Demande de réservation', body: 'Anniversaire 10 pers. samedi?'},
    {app: 'ig', title: 'dorra.b', body: 'chhal el livraison l Sfax?'},
    {app: 'ig', title: 'wassim.tr', body: '??'},
    {app: 'shop', title: 'Nouvelle commande', body: 'Commande #482662 · 96 TND'},
    {app: 'ms', title: 'Asma Jaziri', body: 'famma promo?'},
  ],
  appNames: {ig: 'Instagram', ms: 'Messenger', shop: 'Boutique', resa: 'Réservations'},
  now: 'maintenant',
  // Split panels (Part 1)
  panels: {
    ig: {title: 'Instagram', unit: 'non lus'},
    ms: {title: 'Messenger', unit: 'non lus'},
    shop: {title: 'Nouvelles commandes', unit: 'à traiter'},
    resa: {title: 'Réservations', unit: 'en attente'},
    pending: 'Mazel',
    unanswered: 'Bla jweb',
  },
};

export type NotifApp = 'ig' | 'ms' | 'shop' | 'resa';
