// Generated by scripts/voiceover_gemini.py: seconds where the voice-over speaks.
export const VO_SEGMENTS: [number, number][] = [[0.4, 4.32], [5.3, 8.89], [10.4, 13.13], [16.4, 19.91], [20.4, 24.23], [24.6, 28.45], [29.9, 32.04], [33.2, 35.54], [38.9, 43.27], [45.4, 47.57], [52.0, 56.15], [56.6, 59.47]];
